name: Test Bot Now
 
on:
  workflow_dispatch
 
jobs:
  create-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Create Bot
        run: |
          curl -X POST "https://ap-northeast-1.recall.ai/api/v1/bot/" \
            -H "Content-Type: application/json" \
            -H "Authorization: Token ${{ secrets.TESTAPI }}" \
            -H "accept: application/json" \
            -d '{
              "meeting_url": "${{ secrets.TESTURL }}",
              "bot_name": "Silent Bot",
              "recording_config": {
                "video_mixed_layout": "audio_only",
                "transcript": null,
                "participant_events": {},
                "meeting_metadata": {}
              }
            }'
